version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Lilab.Api/Dockerfile
    ports:
      - "5120:5120"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - data
    command: dotnet Lilab.Api.dll

  service:
    build:
      context: .
      dockerfile: ./Lilab.Service/Dockerfile
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      - data
    command: dotnet Lilab.Service.dll

  data:
    build:
      context: .
      dockerfile: ./Lilab.Data/Dockerfile
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    command: >
      sh -c "
      dotnet ef database update &&
      dotnet Lilab.Data.dll
      "
